### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by ernestkorir** [ernestkorir/movie-shop#21]
Number of members in this project: 2
Project link: https://github.com/users/ernestkorir/projects/18

**Comment by leonardodiasb** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi @ernestkorir, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] Unfortunately, I don't see any projects in the 'Project' section of this Github repository. Kindly follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) to create one, and please paste the link to your GitHub project in this issue.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leonardodiasb** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi @ernestkorir, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

 - Created issues for every task of the project.
 - How many members are participating in the project.

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] I see that you created correctly the issues for the tasks of this project. But, as I mentioned early, you need to create a Kanban Board in the projects section of this Github repository following the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects). The link you provided in this issue redirects to the README page of this project and not the Kanban board in the 'Projects' section. Please add create the project following the instructions and add the link to the project page in this issue.
- Project requirement:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/61919617/204275562-be9d171b-658d-45cd-90b8-e44cdb69f338.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @ernestkorir 🔥 

You worked hard in all the instructions that the previous Code Reviewers gave you 👍🏽 

Now you can close this issue. 🚀 

## Highlights

 - Created issues for every task of the project.
 - How many members are participating in the project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
